version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./site.template:/etc/nginx/conf.d/site.template
      - ./site:/var/www/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=my.domain
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  server:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./mining-pool:/home/node/app
    ports:
      - "8444:8444"
    environment:
      - SERVER_HOST=my.domain
      - SERVER_PORT=8444
    command: /bin/bash -c "npm install && node index.js --config=server.conf"
  
  service:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./mining-pool:/home/node/app
    #ports:
    #  - "8443:8443"
    #  - "8444:8444"
    command: /bin/bash -c "npm install && node index.js --config=service.conf"
