version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./site.template:/etc/nginx/conf.d/site.template
      - ./site:/var/www/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

